.\"
.\"
.\"     lig.1
.\"     
.\"     David Meyer
.\"     dmm@1-4-5.net
.\"     Fri Sep 25 10:54:03 PDT 2009
.\"
.\"
.\"     $Header: /home/dmm/lisp/lig/RCS/lig.1,v 1.3 2009/11/10 05:08:33 dmm Exp $
.\"
.\"
.\"


.TH lig 1  "April 28, 2013" "Version 2.0" "USER COMMANDS"
.SH NAME
lig \- LISP Internet Groper
.SH SYNOPSIS
.TP
.B lig
[-b] [-d] <EID> -m <map resolver/server> [-c <count>] [-p <port>] [-t <timeout>] [-i <IID>] [-v] [--mrauth] [--smri]
.TP
.B lig
-r -m <map resolver/server> --eidpref <EID> --eidmlen <Mask length> --pass <password> [--noproxy] [--mnot] [--recordttl <TTL>] [--notauth] [--mapvers <Map Version>] --locator <RLOC> [--locpr <Priority>] [--locw <Weight>] [--locmpr <MPriority>] [--locmw <MWeight>] [--notreach] --addloc [-v] 

.SH DESCRIPTION
The LISP Internet Groper (lig) 

.SH OPTIONS
.TP
\-b
Print scriptable output
.TP
\-d
display additional debug information
.TP
\-r
If specified, lig will send a Map Register message. If not, it 
will send an Encapsulated Map Request.
.TP
\-m <map resolver/server>
Specify the Map Resolver/Server to send the Map 
Request/Map Register to. The Map Resolver can also be 
specified by setting the LISP_MAP_RESOLVER enviornment variable
to the name (or address) of a Map Resolver.
.TP
\-c <count>
Send <count> Map Requests before giving up. The default value is 3.
.TP
\-p <port>
Set the source port of the inner (encapsulated) UDP header.
.TP
\-t <timeout>
Set the time to wait for a Map Reply (in milliseconds).
.TP
\-i <IID>
Use the specified Instance ID.
.TP
\--mrauth
Set the Map-Request Authoritatuve bit if you want the destination 
site to return the Map-Reply rather than the mapping database system.
.TP
\--smri
Set the SMR-invoked bit. It is cleared by default.
.TP
\--eidpref <EID>
Specify the EID prefix address for the Map Register function.. This 
can be an IPv4 or IPv6 address.
.TP
\--eidmlen <Mask length>
Specify the EID mask length. 
Note: Mustn't be entered before the --eidpref option.
.TP
\--pass <password>
Enter the Map Server password for the HMAC computation
.TP
\--noproxy
Clear the Proxy Reply bit. It is set by default.
.TP
\--mnot
Set the Want Map Notify bit. It is cleared by default.
.TP
\--recordttl <TTL>
Specify the Record Time To Live.
.TP
\--notauth
Clear the Authoritative bit. It is set by default.
.TP
\--mapvers <Map Version>
Specify The Map Version number.
.TP
\--locator <RLOC>
Specify the locator address. IPv4 and IPv6 supported.
Note: Mustn't be entered before the --eidmlen option. 
.TP
\--locpr <Priority>
Specify the locator Priority
.TP
\--locw <Weight>
Specify the locator Weight
.TP
\--locmpr <MPriority>
Specify the locator Multicast Priority
.TP
\--locmw <MWeight>
Specify the locator Multicast Weight
.TP
\--notreach
Clear the locator Reachable bit. It is set by default.
.TP
\--addloc
Adds the locator with all the parameters specified 
between the --locator and the --addloc options and
resets the parameters to their default values for the
next locator.
Note: The --locator and --addloc options must be specified
for each additional locator entry. 
.TP
\-v
Print the lig version. The version string is of the form XXYYZZ
where XX is the base specification version, YY is the Map Server
specification version, and ZZ is the lig code verison. 
.SH EXAMPLES
.TP
.PP
.SH Source Code
http://github.com/alexiuhas/lig
.SH AUTHOR
.IP
David Meyer (dmm at 1-4-5.net)
.IP
Alexandru Iuhas
